#%RAML 1.0
title: Retail Customer Onboarding Process API
version: v2.0
mediaType: application/json
baseUri: https://localhost:8082/api

uses:
  customer: /exchange_modules/org.mule.templates/retail-customer-types/1.0.2/retail_customer_types.raml

types: 
  Customer:
    type: customer.Customer
    properties:
      userId?: 
        type: string
        description: Identifier of user
      customerId?: 
        type: string
        description: Idenitifier of customer
      firstName?: 
        type: string
        description: First name
      lastName: 
        type: string
        description: Last name
      middleName?: 
        type: string
        description: Middle name
      phone?: 
        type: string
        description: Phone number
      email: 
        type: string
        description: Email address
  
  CustomerResponse: 
    type: object
    properties:
      customerId: string
      nativeId: string
  
/customers:
  post:
    displayName: Create customer
    description: Create customer contact  
    body:
      application/json:
        type: Customer
        example: !include examples/post_customer_request.yaml
    responses:
      201:
        body:
          type: CustomerResponse
          example: !include examples/post_customer_response.yaml